### ISSUE TITLE
Getting an exception, because of closed dbreader

### ISSUE THREAD

**Issue by blobor** [StackExchange/dapper-dot-net#157]
Hi!
I'm getting an exception of type "System.InvalidOperationException" with message "Invalid attempt to call FieldCount when reader is closed."

Additional information:
Source: "System.Data"
StackTrace:    
   at System.Data.SqlClient.SqlDataReader.get_FieldCount()
   at Dapper.SqlMapper.GetColumnHash(IDataReader reader) in D:\Dev\dapper-dot-net\Dapper NET40\SqlMapper.cs:line 468
   at Dapper.SqlMapper.<MultiMapImpl>d__14`8.MoveNext() in D:\Dev\dapper-dot-net\Dapper NET40\SqlMapper.cs:line 1719
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Implementation.UserRepository.<QueryPersonsByConditionAsync>d__1b.MoveNext() in UserRepository.cs:line 217

It's reproducing only on async queries with buffered parameter  set to false. If I set true, every thing is fine.

**Comment by NickCraver** [comment]
@blobor were you able to reproduce this?

**Comment by OleksiiYatsenko** [comment]
Hi, I met this problem in this example when i try to 
public async Task<IDictionary<TKey, TValue>> RunQueryToDictionaryAsync<TKey, TValue>(string query, string splitOn, params Tuple<string, object>[] parameters)
        {
            using (var sqlConnection = new SqlConnection(_connectionString))
            {
                await sqlConnection.OpenAsync();

                var result = await sqlConnection.QueryAsync<TKey, TValue, KeyValuePair<TKey, TValue>>(query, (k, v) => new KeyValuePair<TKey, TValue>(k, v), null, null, false, splitOn);

                return result.ToDictionary(x => x.Key, x => x.Value);
            }
        }

If i set buffered to true everything works fine.
