### ISSUE TITLE
Add support for medium trust

### ISSUE THREAD

**Issue by Giorgi** [StackExchange/dapper-dot-net#252]
Medium trust does not allow usage of reflection so the library does not work in most of shared hostings. Is it possible to add workaround so that it works in medium trust?

**Comment by NickCraver** [comment]
I haven't had to deal with medium trust in some time - what are you actually hitting? (e.g. stack traces) I'm not sure the extent of the breaks and if this really feasible, from what I remember is isn't really...but the lockdowns may have changed in the past few years.

**Comment by Giorgi** [comment]
I moved to a different web hosting which provides full trust so I don't have the stacktrace any more.

**Comment by NickCraver** [comment]
Thanks for the update @Giorgi, much appreciated. Medium trust is becoming a thing of the past, so I'll close this out. I think we can forget about the (likely multiple) issues with medium trust unless someone actually hits it again.

**Comment by minto5050** [comment]
@NickCraver  If you want to follow up on this, The stack trace is given below
```
   at System.Security.CodeAccessSecurityEngine.Check(Object demand, StackCrawlMark& stackMark, Boolean isPermSet)
   at System.Security.CodeAccessSecurityEngine.Check(CodeAccessPermission cap, StackCrawlMark& stackMark)
   at System.Security.CodeAccessPermission.Demand()
   at System.Reflection.Emit.DynamicMethod.PerformSecurityCheck(Type owner, StackCrawlMark& stackMark, Boolean skipVisibility)
   at System.Reflection.Emit.DynamicMethod..ctor(String name, Type returnType, Type[] parameterTypes, Type owner, Boolean skipVisibility)
   at Dapper.SqlMapper.GetTypeDeserializerImpl(Type type, IDataReader reader, Int32 startBound, Int32 length, Boolean returnNullIfFirstMissing)
   at Dapper.SqlMapper.TypeDeserializerCache.GetReader(IDataReader reader, Int32 startBound, Int32 length, Boolean returnNullIfFirstMissing)
   at Dapper.SqlMapper.TypeDeserializerCache.GetReader(Type type, IDataReader reader, Int32 startBound, Int32 length, Boolean returnNullIfFirstMissing)
   at Dapper.SqlMapper.GetTypeDeserializer(Type type, IDataReader reader, Int32 startBound, Int32 length, Boolean returnNullIfFirstMissing)
   at Dapper.SqlMapper.GetDeserializer(Type type, IDataReader reader, Int32 startBound, Int32 length, Boolean returnNullIfFirstMissing)
   at Dapper.SqlMapper.<QueryImpl>d__69`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType)
   at KYC_v4.DapperRepository.Repositories.FinalResultRepository.Get(Expression`1 filter, Func`2 orderBy, String includeProperties) in c:\Users\PS\Documents\Visual Studio 2012\Projects\KYC v4\KYC v4\DapperRepository\Repositories\FinalResultRepository.cs:line 60
   at KYC_v4.Controllers.ResultController.Tabular(Int32 id) in c:\Users\PS\Documents\Visual Studio 2012\Projects\KYC v4\KYC v4\Controllers\ResultController.cs:line 474
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.InvokeSynchronousActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass42.<BeginInvokeSynchronousActionMethod>b__41()
   at System.Web.Mvc.Async.AsyncResultWrapper.<>c__DisplayClass8`1.<BeginSynchronous>b__7(IAsyncResult _)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.End()
   at System.Web.Mvc.Async.AsyncResultWrapper.End[TResult](IAsyncResult asyncResult, Object tag)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass37.<>c__DisplayClass39.<BeginInvokeActionMethodWithFilters>b__33()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass4f.<InvokeActionMethodFilterAsynchronously>b__49()
```

**Comment by Kilroy576** [comment]
Ich bin erst wieder ab 12. September wieder im B�ro.

Mit freundlichen Gr��en
Ralf Schoch

------------------------------------------------------------
CoDeSo������������������ Consulting, Development & Solutions
Ralf Schoch������������� phone +49 (0)721 75099567
Freelancer�������������� fax�� +49 (0)721 75099568
Rhode-Island-Allee 85��� mail� ralf.schoch@codeso.de
76149 Karlsruhe��������� web�� http://www.codeso.de/
Germany����������������� blog� http://blog.codeso.de/
------------------------------------------------------------
