### ISSUE TITLE
SqlMapper Issue on Postgres Array After upgrading Npgsql 3.0.1

### ISSUE THREAD

**Issue by robertaves** [StackExchange/dapper-dot-net#330]
getting the below exception when mapping an column of type double[] is postgres once upgrading to npgsql 3.0.1

    System.ArgumentOutOfRangeException: Non-negative number required.
       Parameter name: lengths[0]
       at System.Array.CreateInstance(Type elementType, Int32[] lengths)
       at Npgsql.TypeHandlers.ArrayHandler.Read[TElement](Array& result)
       at Npgsql.TypeHandler.Read[T](NpgsqlBuffer buf, Int32 len, FieldDescription fieldDescription)
       at Npgsql.TypeHandler.Read[T](DataRowMessage row, Int32 len, FieldDescription fieldDescription)
       at Npgsql.TypeHandler`1.ReadValueAsObject(DataRowMessage row, FieldDescription fieldDescription)
       at Npgsql.NpgsqlDataReader.GetValue(Int32 ordinal)
       at Dapper.SqlMapper.<>c__DisplayClass87_0.<GetDapperRowDeserializer>b__0(IDataReader r)
       at Dapper.SqlMapper.<QueryImpl>d__61`1.MoveNext()
       at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
       at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
       at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType)

table is defined as:
    
    CREATE SCHEMA test;
    CREATE TABLE test.foo
    (
      coords double precision[] DEFAULT '{}'::double precision[]
    )
    WITH (
      OIDS=FALSE
    );

This code works ( sans dapper ):

    void Main()
    {
	    using (var conn = new Npgsql.NpgsqlConnection("User ID=postgres;Password=postgres;Host=localhost;Port=5432;Database=postgres;"))
	    {
    		var q = @"select coords from test.foo";
		
	    	conn.Open();
		
		    using (var cmd = new NpgsqlCommand())
		    {
			    cmd.Connection = conn;
	
			    // Insert some data
			    cmd.CommandText = q;
			    cmd.ExecuteNonQuery();	
			
			    using (var reader = cmd.ExecuteReader())
			    {
    				while (reader.Read())
	    			{
		    			Console.WriteLine(reader.GetValue(0));
			    	}
			    }
		    }
	    }
    }

This code throws the above exception (  dapper ):

Note: the exception case below works on a subset of the data: select coords from test.foo limit 100

    void Main()
    {
	    using (var conn = new Npgsql.NpgsqlConnection("User ID=postgres;Password=postgres;Host=localhost;Port=5432;Database=postgres;"))
	    {
		    var q = @"select coords from test.foo";
		    var r = conn.Query(q);		    
	    }
    }

test data was as following:

    insert into test.foo select '{-76.7737808227539,38.6757011413574}'; 
    insert into test.foo select '{-90.2042999267578,38.6061210632324}'; 
    insert into test.foo select '{-99.6109085083008,39.4350204467773}'; 
    insert into test.foo select '{-113.334396362305,53.6272583007812}'; 
    insert into test.foo select '{-78.6930465698242,38.8840293884277}'; 
    insert into test.foo select '{-3.62128710746765,5.33142423629761}'; 
    insert into test.foo select '{121.285598754883,31.0994091033936}'; 
    insert into test.foo select '{-122.620697021484,37.5160102844238}'; 
    insert into test.foo select '{28.8404102325439,-20.1120090484619}'; 
    insert into test.foo select '{-122.92440032959,50.4201202392578}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{-81.1987915039062,42.921028137207}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{-81.1988830566406,42.9208908081055}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{23.8066902160645,37.9938316345215}'; 
    insert into test.foo select '{32.7417984008789,39.8990592956543}'; 
    insert into test.foo select '{121.486099243164,31.2404308319092}'; 
    insert into test.foo select '{12.8903799057007,45.4252815246582}'; 
    insert into test.foo select '{28.7905693054199,-20.197790145874}'; 
    insert into test.foo select '{31.3013000488281,30.2453308105469}'; 
    insert into test.foo select '{27.9280204772949,-26.1442604064941}'; 
    insert into test.foo select '{-7.51214599609375,33.531608581543}'; 
    insert into test.foo select '{18.4077205657959,-33.9961700439453}'; 
    insert into test.foo select '{-4.01052093505859,5.2469310760498}'; 
    insert into test.foo select '{-76.1522598266602,45.5131187438965}'; 
    insert into test.foo select '{-84.0429077148438,26.7216796875}'; 
    insert into test.foo select '{-118.290901184082,34.1620712280273}'; 
    insert into test.foo select '{-113.606002807617,53.6553115844727}'; 
    insert into test.foo select '{-83.7575378417969,42.4012184143066}'; 
    insert into test.foo select '{-104.886901855469,39.7714309692383}'; 
    insert into test.foo select '{-87.8056564331055,41.9187507629395}'; 
    insert into test.foo select '{-82.9099502563477,39.945068359375}'; 
    insert into test.foo select '{-114.065101623535,51.0554084777832}'; 
    insert into test.foo select '{-97.7941970825195,30.2546005249023}'; 
    insert into test.foo select '{-97.8130111694336,30.2590293884277}'; 
    insert into test.foo select '{5.54798221588135,60.3944282531738}'; 
    insert into test.foo select '{1.90804696083069,41.3216781616211}'; 
    insert into test.foo select '{101.894096374512,14.2260599136353}'; 
    insert into test.foo select '{23.7991008758545,37.854549407959}'; 
    insert into test.foo select '{32.6700096130371,39.7541389465332}'; 
    insert into test.foo select '{4.98365879058838,52.3161392211914}'; 
    insert into test.foo select '{151.106796264648,-33.884521484375}'; 
    insert into test.foo select '{-2.01787805557251,57.1758995056152}'; 
    insert into test.foo select '{151.247802734375,-33.8419914245605}'; 
    insert into test.foo select '{-2.01748704910278,57.1339111328125}'; 
    insert into test.foo select '{-2.06198310852051,56.9877815246582}'; 
    insert into test.foo select '{101.130302429199,14.5569400787354}'; 
    insert into test.foo select '{23.7023601531982,37.9377098083496}'; 
    insert into test.foo select '{4.47257280349731,52.3635711669922}'; 
    insert into test.foo select '{150.999206542969,-33.8976593017578}'; 
    insert into test.foo select '{-1.94999396800995,57.1934509277344}'; 
    insert into test.foo select '{-113.620300292969,53.5245590209961}'; 
    insert into test.foo select '{-82.8023529052734,42.3414611816406}'; 
    insert into test.foo select '{-104.97730255127,39.7615699768066}'; 
    insert into test.foo select '{-87.6154937744141,41.8608894348145}'; 
    insert into test.foo select '{-82.9748229980469,39.9586296081543}'; 
    insert into test.foo select '{-114.049301147461,51.0101013183594}'; 
    insert into test.foo select '{-97.734260559082,30.2587108612061}'; 
    insert into test.foo select '{-97.7917633056641,30.2798099517822}'; 
    insert into test.foo select '{138.758605957031,35.3644409179688}'; 
    insert into test.foo select '{5.36941480636597,60.4228706359863}'; 
    insert into test.foo select '{1.83401596546173,41.2943115234375}'; 
    insert into test.foo select '{101.394599914551,14.3086795806885}'; 
    insert into test.foo select '{23.7888793945312,37.9709815979004}'; 
    insert into test.foo select '{32.8272895812988,39.8510513305664}'; 
    insert into test.foo select '{4.89696979522705,52.3622283935547}'; 
    insert into test.foo select '{151.232604980469,-33.8709106445312}'; 
    insert into test.foo select '{-82.8824234008789,39.9307289123535}'; 
    insert into test.foo select '{-114.080497741699,50.9945793151855}'; 
    insert into test.foo select '{-97.7061996459961,30.2164993286133}'; 
    insert into test.foo select '{-97.7708282470703,30.2812690734863}'; 
    insert into test.foo select '{138.785598754883,35.3405685424805}'; 
    insert into test.foo select '{5.41344404220581,60.3865699768066}'; 
    insert into test.foo select '{1.85099494457245,41.2984008789062}'; 
    insert into test.foo select '{101.420799255371,14.3487901687622}'; 
    insert into test.foo select '{23.8163509368896,37.9403190612793}'; 
    insert into test.foo select '{32.7533493041992,39.8677406311035}'; 
    insert into test.foo select '{4.82528781890869,52.4267997741699}'; 
    insert into test.foo select '{151.163192749023,-33.8855209350586}'; 
    insert into test.foo select '{-2.05632090568542,57.1955490112305}'; 
    insert into test.foo select '{-81.0780868530273,42.8536109924316}'; 
    insert into test.foo select '{-76.9125595092773,38.9432907104492}'; 
    insert into test.foo select '{-122.965103149414,50.1353492736816}'; 
    insert into test.foo select '{-123.042701721191,49.2289199829102}'; 
    insert into test.foo select '{-79.4281921386719,43.6438484191895}'; 
    insert into test.foo select '{-122.193702697754,47.6994590759277}'; 
    insert into test.foo select '{-122.456596374512,37.7711906433105}'; 
    insert into test.foo select '{-90.0986633300781,38.5446510314941}'; 
    insert into test.foo select '{-74.2309494018555,40.7718200683594}'; 
    insert into test.foo select '{-72.6048126220703,45.5036315917969}'; 
    insert into test.foo select '{-98.7353363037109,26.6695995330811}'; 
    insert into test.foo select '{-118.298202514648,34.1509284973145}'; 
    insert into test.foo select '{-113.685897827148,53.499568939209}'; 
    insert into test.foo select '{-82.7276229858398,42.3179702758789}'; 
    insert into test.foo select '{-104.874702453613,39.7219314575195}'; 
    insert into test.foo select '{-87.5571899414062,41.9248886108398}'; 
    insert into test.foo select '{-82.9326934814453,39.940601348877}'; 
    insert into test.foo select '{-114.160202026367,51.0281791687012}'; 
    insert into test.foo select '{-97.7817687988281,30.3495407104492}'; 
    insert into test.foo select '{-97.8281402587891,30.3445301055908}'; 
    insert into test.foo select '{138.613296508789,35.3434906005859}'; 
    insert into test.foo select '{5.38837385177612,60.344409942627}'; 
    insert into test.foo select '{1.87468004226685,41.2807693481445}'; 
    insert into test.foo select '{101.815399169922,14.3784999847412}'; 
    insert into test.foo select '{23.7949695587158,37.9983215332031}'; 
    insert into test.foo select '{32.7874412536621,39.8280792236328}'; 
    insert into test.foo select '{4.86728096008301,52.3977088928223}'; 
    insert into test.foo select '{151.320205688477,-33.8185806274414}'; 
    insert into test.foo select '{-2.08501505851746,57.180549621582}'; 
    insert into test.foo select '{-81.1945419311523,42.9242897033691}'; 
    insert into test.foo select '{-76.9189071655273,38.85546875}'; 
    insert into test.foo select '{-122.970100402832,50.0030212402344}'; 
    insert into test.foo select '{-122.507598876953,48.8831405639648}'; 
    insert into test.foo select '{-79.0204162597656,43.723331451416}'; 
    insert into test.foo select '{-121.775398254395,47.4592208862305}'; 
    insert into test.foo select '{-122.533599853516,37.5526008605957}'; 
    insert into test.foo select '{-89.9930267333984,38.6583290100098}'; 
    insert into test.foo select '{-73.9531326293945,40.4677391052246}'; 
    insert into test.foo select '{-66.3715362548828,45.4417114257812}'; 
    insert into test.foo select '{-76.3871536254883,26.7605991363525}'; 
    insert into test.foo select '{-118.376502990723,34.0214004516602}'; 
    insert into test.foo select '{-113.716300964355,53.7390518188477}'; 
    insert into test.foo select '{-81.6156311035156,42.6007690429688}'; 
    insert into test.foo select '{-104.87020111084,39.7314682006836}'; 
    insert into test.foo select '{-87.3603668212891,41.7475204467773}'; 
    insert into test.foo select '{-83.2783203125,40.1121215820312}'; 
    insert into test.foo select '{-113.975196838379,50.8641090393066}'; 
    insert into test.foo select '{-97.1164093017578,30.3550491333008}'; 
    insert into test.foo select '{-95.5495834350586,29.9211807250977}'; 
    insert into test.foo select '{138.698501586914,35.3761711120605}'; 
    insert into test.foo select '{5.66097116470337,60.4660491943359}'; 
    insert into test.foo select '{1.83401894569397,41.2801208496094}'; 
    insert into test.foo select '{100.860900878906,14.4449901580811}'; 
    insert into test.foo select '{23.7179698944092,37.7372398376465}'; 
    insert into test.foo select '{32.6968193054199,39.9893798828125}'; 
    insert into test.foo select '{3.82396292686462,52.2260704040527}'; 
    insert into test.foo select '{151.270706176758,-33.9169998168945}'; 
    insert into test.foo select '{-1.56644797325134,57.0703582763672}'; 
    insert into test.foo select '{-80.7333068847656,42.9519882202148}'; 
    insert into test.foo select '{-77.4140319824219,39.1175117492676}'; 
    insert into test.foo select '{-122.961502075195,50.1557502746582}'; 
    insert into test.foo select '{-123.249198913574,49.2787399291992}'; 
    insert into test.foo select '{-79.7025985717773,43.7375297546387}'; 
    insert into test.foo select '{-122.044097900391,47.464958190918}'; 
    insert into test.foo select '{-122.19450378418,37.7334899902344}'; 
    insert into test.foo select '{-90.3339309692383,38.6133308410645}'; 
    insert into test.foo select '{-74.1081466674805,41.0290412902832}'; 
    insert into test.foo select '{-93.4581604003906,45.7471885681152}'; 
    insert into test.foo select '{-89.1957626342773,26.7025108337402}'; 
    insert into test.foo select '{-118.133003234863,34.2357597351074}'; 
    insert into test.foo select '{-113.51969909668,53.3103294372559}'; 
    insert into test.foo select '{-202.744506835938,42.707820892334}'; 
    insert into test.foo select '{-105.009696960449,39.6916809082031}'; 
    insert into test.foo select '{-87.6537780761719,41.9507598876953}'; 
    insert into test.foo select '{-82.9586791992188,39.8707389831543}'; 
    insert into test.foo select '{-113.957298278809,50.7921295166016}'; 
    insert into test.foo select '{-98.2949676513672,30.1087799072266}'; 
    insert into test.foo select '{1.17117202281952,41.2270393371582}'; 
    insert into test.foo select '{99.188362121582,14.3281898498535}'; 
    insert into test.foo select '{24.1315097808838,38.2411994934082}'; 
    insert into test.foo select '{32.4065704345703,39.9020614624023}'; 
    insert into test.foo select '{2.99215006828308,52.608081817627}'; 
    insert into test.foo select '{150.994094848633,-34.1432418823242}'; 
    insert into test.foo select '{-1.94963705539703,56.8954010009766}'; 
    insert into test.foo select '{-80.7945938110352,43.1559906005859}'; 
    insert into test.foo select '{111.387496948242,39.1437492370605}'; 
    insert into test.foo select '{-122.228103637695,50.4581298828125}'; 
    insert into test.foo select '{-122.670303344727,49.608081817627}'; 
    insert into test.foo select '{-79.1592788696289,43.7664108276367}'; 
    insert into test.foo select '{-122.963401794434,47.7581596374512}'; 
    insert into test.foo select '{-122.065696716309,37.881591796875}'; 
    insert into test.foo select '{-89.4264373779297,39.1164207458496}'; 
    insert into test.foo select '{-74.5949783325195,40.9845085144043}'; 
    insert into test.foo select '{-95.5734481811523,45.4954795837402}'; 
    insert into test.foo select '{-73.9963684082031,26.7970199584961}'; 
    insert into test.foo select '{-118.852203369141,34.3647003173828}'; 
    insert into test.foo select '{-113.931098937988,53.3658294677734}'; 
    insert into test.foo select '{-85.1255035400391,42.4605598449707}'; 
    insert into test.foo select '{-105.467498779297,39.8251113891602}'; 
    insert into test.foo select '{-88.1532897949219,42.1672401428223}'; 
    insert into test.foo select '{-83.57958984375,40.17578125}'; 
    insert into test.foo select '{-113.62809753418,51.1468696594238}'; 
    insert into test.foo select '{-96.567741394043,30.2958106994629}'; 
    insert into test.foo select '{-96.759880065918,30.482250213623}'; 
    insert into test.foo select '{138.175201416016,35.3951797485352}'; 
    insert into test.foo select '{5.2697548866272,60.4524192810059}'; 
    insert into test.foo select '{1.70064198970795,41.4422416687012}'; 
    insert into test.foo select '{97.2627029418945,14.3355798721313}'; 
    insert into test.foo select '{24.3660697937012,38.3582382202148}'; 
    insert into test.foo select '{31.9810009002686,40.1504898071289}'; 
    insert into test.foo select '{4.42320680618286,52.423168182373}'; 
    insert into test.foo select '{150.700897216797,-33.9645385742188}'; 
    insert into test.foo select '{-1.8338680267334,57.026798248291}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{138.692596435547,35.3722305297852}'; 
    insert into test.foo select '{5.41480398178101,60.3722114562988}'; 
    insert into test.foo select '{-2.07946705818176,57.1353912353516}'; 
    insert into test.foo select '{1.78253304958344,41.2735404968262}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{}'; 
    insert into test.foo select '{1.83979499340057,41.2768402099609}'; 
    insert into test.foo select '{101.552803039551,14.3863401412964}'; 
    insert into test.foo select '{-2.01143193244934,57.0898704528809}'; 
    insert into test.foo select '{23.8067607879639,38.0105895996094}'; 
    insert into test.foo select '{32.8121910095215,39.8667602539062}'; 
    insert into test.foo select '{4.87010717391968,52.3333702087402}'; 
    insert into test.foo select '{151.257202148438,-33.8262710571289}'; 
    insert into test.foo select '{151.223602294922,-33.8550605773926}'; 
    insert into test.foo select '{-3.59927701950073,56.9831504821777}'; 
    insert into test.foo select '{-81.1614990234375,43.00537109375}'; 
    insert into test.foo select '{-81.1290893554688,42.9830703735352}'; 
    insert into test.foo select '{-81.2272262573242,42.9821395874023}'; 
    insert into test.foo select '{-81.2858123779297,42.9494094848633}'; 
    insert into test.foo select '{-81.3666915893555,43.0444984436035}'; 
    insert into test.foo select '{-81.3008499145508,42.945140838623}'; 
    insert into test.foo select '{-81.4339828491211,43.0208702087402}'; 
    insert into test.foo select '{-81.1787261962891,43.0207099914551}'; 
    insert into test.foo select '{-81.2256469726562,42.9317092895508}'; 
    insert into test.foo select '{-81.2798461914062,43.0100898742676}'; 
    insert into test.foo select '{-81.2516632080078,42.9832992553711}'; 
    insert into test.foo select '{-81.2741775512695,42.9671516418457}'; 
    insert into test.foo select '{-81.2333068847656,42.9743194580078}'; 
    insert into test.foo select '{-81.2208023071289,43.0282096862793}'; 
    insert into test.foo select '{-81.2258987426758,43.0116386413574}'; 
    insert into test.foo select '{-81.2690811157227,42.9923515319824}'; 
    insert into test.foo select '{33.0705795288086,39.7396697998047}'; 
    insert into test.foo select '{-81.25069,43}'; 
    insert into test.foo select '{-81.25069,43}';

**Comment by robertaves** [comment]
This was an issue in Npgsql array mapping.

see issue https://github.com/npgsql/npgsql/issues/733
