### ISSUE TITLE
Query sporadically throws NullReferenceException

### ISSUE THREAD

**Issue by StanBPublic** [StackExchange/dapper-dot-net#340]
This code runs fine
```
// ..
_db = new SqlConnection(connectionString);
// ...
 var parameters = new DynamicParameters();
 parameters.Add("@clientId", clientId);
 return _db.Query<Client>("GetClient", parameters, commandType: CommandType.StoredProcedure).SingleOrDefault();
```

but periodically throws NullReferenceException (abbreviated):

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Dapper.SqlMapper.<QueryImpl>d__11`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType)
```

How can I troubleshoot it further?

**Comment by RoseLiu** [comment]
parameters.Add("@clientId", clientId , DbType.Int32);
or 
parameters.Add("@clientId", clientId , DbType.Guid);

**Comment by StanBPublic** [comment]
This was caused by concurrent threads accessing shared SqlConnection. It doesn't seem to be Daper problem.
