### ISSUE TITLE
Microsoft.Data.Sqlite and CommandBehavior.SingleResult throws exception

### ISSUE THREAD

**Issue by AdamDotNet** [StackExchange/dapper-dot-net#466]
See https://github.com/StackExchange/dapper-dot-net/blob/master/Dapper/SqlMapper.Async.cs#L210

NuGets:
Microsoft.Data.Sqlite 1.0.0-rc1-final
Microsoft.Extensions.PlatformAbstractions 1.0.0-rc1-final

dapper-dot-net master branch

I am trying to retrieve a list of entries from a table.
``` C#
columnMaps = (await connection.QueryAsync<ColumnMap>("SELECT column_id, column_name, ordinal, data_type, variable_type FROM column_map ORDER BY ordinal;").ConfigureAwait(false)).ToList();
```

This exception is thrown.
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.<ExecuteDbDataReaderAsync>d__52.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Dapper.SqlMapper.<QueryAsync>d__22`1.MoveNext() in D:\GitHub\dapper-dot-net\Dapper\SqlMapper.Async.cs:line 210

Removing `CommandBehavior.SingleResult` worked, though that is obviously not the universal answer.

**Comment by mgravell** [comment]
This is actually a sqlite provider bug; a PR for this has been merged. I
get that it is vexing, though. I'm tempted to try and detect this error,
set a global flag, and retry (not setting this in future). This would mean
that it works with the optimisation when fixed at the provider.

**Comment by AdamDotNet** [comment]
Fair enough! I was wondering if bugs with Dapper were actually bugs with a pre-release version of SQLite. I'll go ahead and close this one and watch for a new SQLite release.

**Comment by mgravell** [comment]
@AdamDotNet I added a workaround for this into the code. Of course, that doesn't help if the parameters refuse to work at all (#467), but ... *this bit* won't bite after the next build ;)

**Comment by AdamDotNet** [comment]
Cool, thanks!

**Comment by mgravell** [comment]
For reference: https://github.com/aspnet/Microsoft.Data.Sqlite/issues/220 / https://github.com/aspnet/Microsoft.Data.Sqlite/pull/221

**Comment by mgravell** [comment]
deployed 1.50-beta9
