### ISSUE TITLE
Dapper trying to parse wrong column

### ISSUE THREAD

**Issue by v0l** [StackExchange/dapper-dot-net#576]
Run into a small issue with dapper trying to map the previous column to the wrong field in the class and as such is throwing "Specified cast is not valid". 

![exception](https://void.cat/f1f4bc2e234e5830b0cb0f73f07ab3a7e2a7dcad)

![row](https://void.cat/081a41887ee4e7e6d4525e7f43dd5e1ac3a10f02)

```
   at Dapper.SqlMapper.ThrowDataException(Exception ex, Int32 index, IDataReader reader, Object value)
   at Deserialize04ea767d-0f4a-4b86-ab84-f46ff296e65f(IDataReader )
   at Dapper.SqlMapper.<QueryImpl>d__125`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType)
```

Inner exception 

```
     at Oracle.ManagedDataAccess.Client.OracleDataReader.GetDecimal(Int32 i)
   at Oracle.ManagedDataAccess.Client.OracleDataReader.GetValue(Int32 i)
   at Oracle.ManagedDataAccess.Client.OracleDataReader.get_Item(Int32 i)
   at Deserialize04ea767d-0f4a-4b86-ab84-f46ff296e65f(IDataReader )
```

Nuget package version s

```
<package id="Oracle.ManagedDataAccess" version="12.1.24160419" targetFramework="net45" />
<package id="Dapper" version="1.50.2" targetFramework="net45" />
```

**Comment by v0l** [comment]
After some digging this appears to be an issue with OracleDataReader.

Its attempting to parse NUMBER as [decimal](https://msdn.microsoft.com/en-us/library/364x0z75.aspx) but the max precision is 28-29?

This error message with "PRICE=L" is just an incorrect error. It was attempting to parse the correct column.

```
create table test2 ( test NUMBER );
insert into test2 values(0.36363636363636363636363636363636363636);
commit;
--Try the select * from test2; this will fail

update test2 set test = 0.3636363636363636363636363636;
commit;
--this one will work fine

```

**Comment by NickCraver** [comment]
Since this is really an Oracle problem, I'm not sure there's anything we can do about the root exception here, unfortunately. If the error message is off in the current version, that certainly needs a fix though.

**Comment by NickCraver** [comment]
Any update here?

**Comment by cottsak** [comment]
I think this is rather [Microsoft's implementation](https://msdn.microsoft.com/en-us/library/yk72thhd.aspx) that's at fault: always trying to [cast to a Decimal, when sometimes that won't work](https://chrismay.org/2015/07/30/bug-in-oracledatareader-causing-invalidcastexception).
