### ISSUE TITLE
OutOfMemoryException

### ISSUE THREAD

**Issue by keep01** [StackExchange/dapper-dot-net#599]
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Runtime.CompilerServices.RuntimeHelpers._CompileMethod(IRuntimeMethodInfo method)
   at System.Reflection.Emit.DynamicMethod.CreateDelegate(Type delegateType)
   at ET.Core.DataAccess.SqlMapper.GetTypeDeserializer(Type type, IDataReader reader, Int32 startBound, Int32 length, Boolean returnNullIfFirstMissing)
   at ET.Core.DataAccess.SqlMapper.GetDeserializer(Type type, IDataReader reader, Int32 startBound, Int32 length, Boolean returnNullIfFirstMissing)
   at ET.Core.DataAccess.SqlMapper.<QueryInternal>d__d`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ET.Core.DataAccess.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType)

sql="select * from IMAGE where SOP_INSTANCE_UID='1.2.392.200036.9116.2.5.1.3268.2059598828.1471478344.464589'"

Repeat 5000000 times.

**Comment by mgravell** [comment]
Are you building and issuing non-parameterized sql? Because yes, that would
do bad things. Can I see the actual calling code? Assuming the id changes
each time, you might want:

    string id = "1.2.392.200036.9116.2.5.1.3268.2059598828
.1471478344.464589";
sql="select * from IMAGE where SOP_INSTANCE_UID=@id"

Passing `new { id }` as the parameters object.

**Comment by mgravell** [comment]
Note: if you need fine-grained control over varchar vs nvarchar, that's
available too - just let me know.

**Comment by mgravell** [comment]
Closing; I'm assuming this is indeed lack of parameterization; if I'm wrong, let me know - will re-open
