### ISSUE TITLE
Exception in Dapper.Contrib SqlMapperExtension during the Insert "Value was either too large or too small for an Int32"

### ISSUE THREAD

**Issue by suresh105** [StackExchange/dapper-dot-net#610]
**Scenario:**
When explicitly inserting long value in primary key non identity column getting exception as "Value was either too large or too small for an Int32"

**Method:** 
During the insert, the intermittent value stored in int and later i.e. before returning the value its  being converted to long.

long Insert<T>(this IDbConnection connection, T entityToInsert, IDbTransaction transaction = null, int? commandTimeout = null) where T : class

**Please find the highlighted information.**

![capture](https://cloud.githubusercontent.com/assets/4365649/18472961/f17de0d0-79d7-11e6-845c-fac0d9dfdfd1.PNG)

Could somebody help me on this.

**StackTrace:**
at System.Decimal.ToInt32(Decimal d)
at System.Decimal.op_Explicit(Decimal value)
at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
at SqlServerAdapter.Insert(IDbConnection connection, IDbTransaction transaction, Nullable`1 commandTimeout, String tableName, String columnList, String parameterList, IEnumerable`1 keyProperties, Object entityToInsert)
at Dapper.Contrib.Extensions.SqlMapperExtensions.Insert[T](IDbConnection connection, T entityToInsert, IDbTransaction transaction, Nullable`1 commandTimeout)

**Comment by philn5d** [comment]
Looks like there's a decimal being cast to an Int32 in the stack trace you've posted there is that correct? Any idea where the decimal comes from? Plus would help if you posted the entity definition and the actual value that is causing the exception.

**Comment by pjsvis** [comment]
I have made a pull request with a fix for this at https://github.com/StackExchange/dapper-dot-net/pull/640
