### ISSUE TITLE
  A strange exception!!! using  dapper version 1.50.2.0

### ISSUE THREAD

**Issue by onestudy** [StackExchange/dapper-dot-net#635]
My method body:
```C#
public async Task<GetCloudQuestionsOutput> GetCloudQuestionsByKnowledge(GetCloudQuestionsByKnowledgeInput input) {
    int pageSize = 10;
    string sql = string.Empty;

    StringBuilder attachCondition = new StringBuilder();
    if (input.QuestionTypeID.HasValue)
        attachCondition.AppendFormat(" AND QuestionTypeID = {0}", input.QuestionTypeID.Value);
    if (input.AbilityTestID.HasValue)
        attachCondition.AppendFormat(" AND AbilityTestID = {0}", input.AbilityTestID.Value);
    if (input.QuestionDifficultID.HasValue)
        attachCondition.AppendFormat(" AND QuestionDifficultID = {0}", input.QuestionDifficultID.Value);

    if (input.KnowledgeID.HasValue) {
        sql = $@"SELECT SQL_NO_CACHE t.* FROM cloudquestion AS t INNER JOIN cloudquestionknowledgerelation AS r ON t.CloudQuestionID = r.CloudQuestionID WHERE r.KnowledgeID = {input.KnowledgeID.Value} AND t.LearningStageSubjectRID = @LearningStageSubjectRID {attachCondition.ToString()} LIMIT { (input.PageIndex - 1) * pageSize }, {pageSize}";
    }
    else {
        sql = $@"SELECT SQL_NO_CACHE * FROM cloudquestion WHERE LearningStageSubjectRID = @LearningStageSubjectRID {attachCondition.ToString()} LIMIT { (input.PageIndex - 1) * pageSize }, {pageSize}";
    }

    var cloudQuestions = await DB.CloudQuestionRepo.QueryAsync<Domain.CloudQuestion>(sql, input);

    return new GetCloudQuestionsOutput {
        PageIndex = input.PageIndex,
        Questions = cloudQuestions
    };
}
```

Exception message:
```
2016-10-31 11:20:56.2090=> WebApiCustomHandleError?????:   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BKBCloud.Service.CloudQuestion.CloudQuestionService.<GetCloudQuestionsByKnowledge>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BKBCloud.Portal.Api.CloudQuestion.CloudQuestionController.<GetCloudQuestionsByKnowledge>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.AuthenticationFilterResult.<ExecuteAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
```

**Comment by mgravell** [comment]
This looks like a MySql bug. Is there anything that makes you think dapper is part of the problem here?

**Comment by onestudy** [comment]
I use the MySQL 5.6 and 5.7, there will be such a problem. How can I be sure it's MySQL instead of dapper?

**Comment by NickCraver** [comment]
This is an aside but very important: you should be using parameterization for your SQL (not formating values directly in). You can use `DynamicParameters` to build them up, or even use `Dapper.SqlBuilder` (or your own code) for more complex queries. 

For example: `AND QuestionTypeID = @QuestionTypeID` instead of `AND QuestionTypeID = {0}`, you're already passing the parameters you need all the way down.

**Comment by NickCraver** [comment]
Closing out due to inactivity (and not a Dapper library issue)
